services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  init-kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - kafka
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      sleep 20 &&
      kafka-topics --bootstrap-server kafka:29092 --list &&
      kafka-topics --create --if-not-exists --topic order_topic --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1 &&
      kafka-topics --create --if-not-exists --topic inventory_topic --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1
      "
    

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8083:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092

  kouncil:
    image: consdata/kouncil:1.7
    container_name: kouncil
    ports:
      - "8085:8080"
    environment:
      - KOUNCIL_KAFKA_CLUSTERS_0_NAME=local
      - KOUNCIL_KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092